import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AspectThemeProvider } from '@/components/ThemeProvider'
import Navbar from '@/components/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-primary-50 dark:bg-primary-950`} suppressHydrationWarning={true}>
        <AspectThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          <Navbar />
          {children}
          </AspectThemeProvider>
          </body>
    </html>
  )
}
